spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_service
    username: postgres
    password: khoaidaica123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: AuthService

server:
  port: 8081


